version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: college_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=college
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: college_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/college?schema=public
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

volumes:
  db_data:


